/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xiaorong' at '4/7/16 12:37 PM' with Gradle 2.9
 *
 * @author xiaorong, @date 4/7/16 12:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
